apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-service
  labels:
    app: nodejs-app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app-service
  template:
    metadata:
      labels:
        app: nodejs-app-service
    spec:
      containers:
      - name: nodejs-app-service
        image: techserve4u/nodejs-backend:0.0.1
        imagePullPolicy: Always
